import { Train, Station, StationStatus } from "@/types/train";
import { GeographicLandmark, StationAmenityItem } from "@/types/route";

export const STATIONS_DATABASE: Record<string, Station> = {
  NDLS: {
    id: "NDLS",
    code: "NDLS",
    name: "New Delhi",
    city: "New Delhi",
    state: "Delhi",
    latitude: 28.6431,
    longitude: 77.2197,
    elevationMeters: 216,
    platformCount: 16,
  },
  CNB: {
    id: "CNB",
    code: "CNB",
    name: "Kanpur Central",
    city: "Kanpur",
    state: "Uttar Pradesh",
    latitude: 26.4537,
    longitude: 80.3512,
    elevationMeters: 126,
    platformCount: 10,
  },
  PRYJ: {
    id: "PRYJ",
    code: "PRYJ",
    name: "Prayagraj Jn",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    latitude: 25.4497,
    longitude: 81.8282,
    elevationMeters: 98,
    platformCount: 10,
  },
  BSB: {
    id: "BSB",
    code: "BSB",
    name: "Varanasi Jn",
    city: "Varanasi",
    state: "Uttar Pradesh",
    latitude: 25.3283,
    longitude: 82.9866,
    elevationMeters: 77,
    platformCount: 9,
  },
  MMCT: {
    id: "MMCT",
    code: "MMCT",
    name: "Mumbai Central",
    city: "Mumbai",
    state: "Maharashtra",
    latitude: 18.9712,
    longitude: 72.8197,
    elevationMeters: 14,
    platformCount: 9,
  },
  BVI: {
    id: "BVI",
    code: "BVI",
    name: "Borivali",
    city: "Mumbai",
    state: "Maharashtra",
    latitude: 19.2288,
    longitude: 72.8569,
    elevationMeters: 18,
    platformCount: 8,
  },
  ST: {
    id: "ST",
    code: "ST",
    name: "Surat",
    city: "Surat",
    state: "Gujarat",
    latitude: 21.2052,
    longitude: 72.8407,
    elevationMeters: 17,
    platformCount: 4,
  },
  BRC: {
    id: "BRC",
    code: "BRC",
    name: "Vadodara Jn",
    city: "Vadodara",
    state: "Gujarat",
    latitude: 22.3107,
    longitude: 73.1812,
    elevationMeters: 36,
    platformCount: 7,
  },
  RTM: {
    id: "RTM",
    code: "RTM",
    name: "Ratlam Jn",
    city: "Ratlam",
    state: "Madhya Pradesh",
    latitude: 23.3441,
    longitude: 75.0397,
    elevationMeters: 494,
    platformCount: 7,
  },
  KOTA: {
    id: "KOTA",
    code: "KOTA",
    name: "Kota Jn",
    city: "Kota",
    state: "Rajasthan",
    latitude: 25.2185,
    longitude: 75.8648,
    elevationMeters: 253,
    platformCount: 6,
  },
  SWM: {
    id: "SWM",
    code: "SWM",
    name: "Sawai Madhopur Jn",
    city: "Sawai Madhopur",
    state: "Rajasthan",
    latitude: 25.9934,
    longitude: 76.3688,
    elevationMeters: 266,
    platformCount: 4,
  },
  MTJ: {
    id: "MTJ",
    code: "MTJ",
    name: "Mathura Jn",
    city: "Mathura",
    state: "Uttar Pradesh",
    latitude: 27.4924,
    longitude: 77.6737,
    elevationMeters: 177,
    platformCount: 10,
  },
  NZM: {
    id: "NZM",
    code: "NZM",
    name: "Hazrat Nizamuddin",
    city: "New Delhi",
    state: "Delhi",
    latitude: 28.5889,
    longitude: 77.2536,
    elevationMeters: 207,
    platformCount: 7,
  },
  AGC: {
    id: "AGC",
    code: "AGC",
    name: "Agra Cantt",
    city: "Agra",
    state: "Uttar Pradesh",
    latitude: 27.1587,
    longitude: 77.9904,
    elevationMeters: 167,
    platformCount: 6,
  },
  GWL: {
    id: "GWL",
    code: "GWL",
    name: "Gwalior Jn",
    city: "Gwalior",
    state: "Madhya Pradesh",
    latitude: 26.2163,
    longitude: 78.1887,
    elevationMeters: 212,
    platformCount: 4,
  },
  VGLJ: {
    id: "VGLJ",
    code: "VGLJ",
    name: "Virangana Lakshmibai Jhansi",
    city: "Jhansi",
    state: "Uttar Pradesh",
    latitude: 25.4484,
    longitude: 78.5685,
    elevationMeters: 258,
    platformCount: 8,
  },
  BPL: {
    id: "BPL",
    code: "BPL",
    name: "Bhopal Jn",
    city: "Bhopal",
    state: "Madhya Pradesh",
    latitude: 23.2678,
    longitude: 77.4126,
    elevationMeters: 505,
    platformCount: 6,
  },
  LKO: {
    id: "LKO",
    code: "LKO",
    name: "Lucknow Charbagh",
    city: "Lucknow",
    state: "Uttar Pradesh",
    latitude: 26.8315,
    longitude: 80.9234,
    elevationMeters: 123,
    platformCount: 9,
  },
  LJN: {
    id: "LJN",
    code: "LJN",
    name: "Lucknow Junction",
    city: "Lucknow",
    state: "Uttar Pradesh",
    latitude: 26.8311,
    longitude: 80.9221,
    elevationMeters: 123,
    platformCount: 6,
  },
  MB: {
    id: "MB",
    code: "MB",
    name: "Moradabad Jn",
    city: "Moradabad",
    state: "Uttar Pradesh",
    latitude: 28.8386,
    longitude: 78.7733,
    elevationMeters: 193,
    platformCount: 7,
  },
  BE: {
    id: "BE",
    code: "BE",
    name: "Bareilly Jn",
    city: "Bareilly",
    state: "Uttar Pradesh",
    latitude: 28.3374,
    longitude: 79.4187,
    elevationMeters: 169,
    platformCount: 5,
  },
  HWH: {
    id: "HWH",
    code: "HWH",
    name: "Howrah Jn",
    city: "Kolkata",
    state: "West Bengal",
    latitude: 22.585,
    longitude: 88.3426,
    elevationMeters: 12,
    platformCount: 23,
  },
  MAS: {
    id: "MAS",
    code: "MAS",
    name: "MGR Chennai Central",
    city: "Chennai",
    state: "Tamil Nadu",
    latitude: 13.0827,
    longitude: 80.2707,
    elevationMeters: 10,
    platformCount: 17,
  },
  SBC: {
    id: "SBC",
    code: "SBC",
    name: "KSR Bengaluru",
    city: "Bengaluru",
    state: "Karnataka",
    latitude: 12.9781,
    longitude: 77.5696,
    elevationMeters: 920,
    platformCount: 10,
  },
};

export const TRAINS_DATABASE: Train[] = [
  {
    id: "22436",
    number: "22436",
    name: "Vande Bharat Express",
    type: "Vande Bharat",
    origin: STATIONS_DATABASE.NDLS,
    destination: STATIONS_DATABASE.BSB,
    departureTime: "06:00",
    arrivalTime: "14:00",
    duration: "08h 00m",
    totalDistanceKm: 759,
    runsOnDays: ["Tue", "Wed", "Fri", "Sat", "Sun"],
    runsToday: true,
    classes: ["EC", "CC"],
    pantryAvailable: true,
  },
  {
    id: "12951",
    number: "12951",
    name: "Mumbai Central - New Delhi Rajdhani Express",
    type: "Rajdhani",
    origin: STATIONS_DATABASE.MMCT,
    destination: STATIONS_DATABASE.NDLS,
    departureTime: "17:00",
    arrivalTime: "08:35",
    duration: "15h 35m",
    totalDistanceKm: 1386,
    runsOnDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    runsToday: true,
    classes: ["1A", "2A", "3A", "3E"],
    pantryAvailable: true,
  },
  {
    id: "12004",
    number: "12004",
    name: "New Delhi - Lucknow Swarn Shatabdi",
    type: "Shatabdi",
    origin: STATIONS_DATABASE.NDLS,
    destination: STATIONS_DATABASE.LKO,
    departureTime: "06:10",
    arrivalTime: "12:40",
    duration: "06h 30m",
    totalDistanceKm: 512,
    runsOnDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    runsToday: true,
    classes: ["EC", "CC"],
    pantryAvailable: true,
  },
  {
    id: "12002",
    number: "12002",
    name: "New Delhi - Bhopal Shatabdi Express",
    type: "Shatabdi",
    origin: STATIONS_DATABASE.NDLS,
    destination: STATIONS_DATABASE.BPL,
    departureTime: "06:00",
    arrivalTime: "14:05",
    duration: "08h 05m",
    totalDistanceKm: 707,
    runsOnDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    runsToday: true,
    classes: ["EC", "CC"],
    pantryAvailable: true,
  },
  {
    id: "12229",
    number: "12229",
    name: "Lucknow Mail",
    type: "Mail",
    origin: STATIONS_DATABASE.LJN,
    destination: STATIONS_DATABASE.NDLS,
    departureTime: "22:00",
    arrivalTime: "06:55",
    duration: "08h 55m",
    totalDistanceKm: 493,
    runsOnDays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    runsToday: true,
    classes: ["1A", "2A", "3A", "SL"],
    pantryAvailable: false,
  },

];

export const TRAIN_SCHEDULES: Record<string, StationStatus[]> = {
  // 22436 Vande Bharat: NDLS -> CNB -> PRYJ -> BSB
  "22436": [
    {
      station: STATIONS_DATABASE.NDLS,
      stopSequence: 1,
      scheduledDeparture: "06:00 AM",
      actualDeparture: "06:00 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 0,
      platform: 16,
      status: "COMPLETED",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.CNB,
      stopSequence: 2,
      scheduledArrival: "10:08 AM",
      actualArrival: "10:08 AM",
      estimatedArrival: "10:45 AM",
      scheduledDeparture: "10:12 AM",
      actualDeparture: "10:12 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 440,
      platform: 5,
      status: "CURRENT",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: false },
    },
    {
      station: STATIONS_DATABASE.PRYJ,
      stopSequence: 3,
      scheduledArrival: "12:18 PM",
      estimatedArrival: "12:55 PM",
      scheduledDeparture: "12:20 PM",
      delayMinutes: 0,
      distanceFromOriginKm: 635,
      platform: 4,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: false, pharmacy: false },
    },
    {
      station: STATIONS_DATABASE.BSB,
      stopSequence: 4,
      scheduledArrival: "02:00 PM",
      estimatedArrival: "02:30 PM",
      delayMinutes: 0,
      distanceFromOriginKm: 759,
      platform: 1,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
  ],

  // 12951 Mumbai Central -> New Delhi Rajdhani
  "12951": [
    {
      station: STATIONS_DATABASE.MMCT,
      stopSequence: 1,
      scheduledDeparture: "05:00 PM",
      actualDeparture: "05:12 PM",
      delayMinutes: 12,
      distanceFromOriginKm: 0,
      platform: 1,
      status: "COMPLETED",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.BVI,
      stopSequence: 2,
      scheduledArrival: "05:28 PM",
      actualArrival: "05:40 PM",
      scheduledDeparture: "05:30 PM",
      actualDeparture: "05:42 PM",
      delayMinutes: 12,
      distanceFromOriginKm: 30,
      platform: 6,
      status: "COMPLETED",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: false, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.ST,
      stopSequence: 3,
      scheduledArrival: "07:53 PM",
      actualArrival: "08:08 PM",
      scheduledDeparture: "07:58 PM",
      actualDeparture: "08:13 PM",
      delayMinutes: 15,
      distanceFromOriginKm: 263,
      platform: 1,
      status: "COMPLETED",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.BRC,
      stopSequence: 4,
      scheduledArrival: "09:28 PM",
      estimatedArrival: "09:46 PM",
      scheduledDeparture: "09:38 PM",
      delayMinutes: 18,
      distanceFromOriginKm: 392,
      platform: 2,
      status: "CURRENT",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.RTM,
      stopSequence: 5,
      scheduledArrival: "01:00 AM",
      estimatedArrival: "01:16 AM",
      scheduledDeparture: "01:05 AM",
      delayMinutes: 16,
      distanceFromOriginKm: 653,
      platform: 4,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: false, pharmacy: false },
    },
    {
      station: STATIONS_DATABASE.KOTA,
      stopSequence: 6,
      scheduledArrival: "04:00 AM",
      estimatedArrival: "04:14 AM",
      scheduledDeparture: "04:10 AM",
      delayMinutes: 14,
      distanceFromOriginKm: 920,
      platform: 1,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.SWM,
      stopSequence: 7,
      scheduledArrival: "05:18 AM",
      estimatedArrival: "05:30 AM",
      scheduledDeparture: "05:20 AM",
      delayMinutes: 12,
      distanceFromOriginKm: 1028,
      platform: 1,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: false, lounge: false, pharmacy: false },
    },
    {
      station: STATIONS_DATABASE.NDLS,
      stopSequence: 8,
      scheduledArrival: "08:35 AM",
      estimatedArrival: "08:50 AM",
      delayMinutes: 15,
      distanceFromOriginKm: 1386,
      platform: 14,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
  ],

  // 12004 Swarn Shatabdi: NDLS -> CNB -> LKO
  "12004": [
    {
      station: STATIONS_DATABASE.NDLS,
      stopSequence: 1,
      scheduledDeparture: "06:10 AM",
      actualDeparture: "06:10 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 0,
      platform: 1,
      status: "COMPLETED",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.CNB,
      stopSequence: 2,
      scheduledArrival: "11:20 AM",
      estimatedArrival: "11:20 AM",
      scheduledDeparture: "11:25 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 440,
      platform: 6,
      status: "CURRENT",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.LKO,
      stopSequence: 3,
      scheduledArrival: "12:40 PM",
      estimatedArrival: "12:40 PM",
      delayMinutes: 0,
      distanceFromOriginKm: 512,
      platform: 2,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
  ],

  // 12002 Bhopal Shatabdi: NDLS -> MTJ -> AGC -> GWL -> VGLJ -> BPL
  "12002": [
    {
      station: STATIONS_DATABASE.NDLS,
      stopSequence: 1,
      scheduledDeparture: "06:00 AM",
      actualDeparture: "06:00 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 0,
      platform: 1,
      status: "COMPLETED",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.MTJ,
      stopSequence: 2,
      scheduledArrival: "07:19 AM",
      actualArrival: "07:19 AM",
      scheduledDeparture: "07:20 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 141,
      platform: 1,
      status: "COMPLETED",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: false, pharmacy: false },
    },
    {
      station: STATIONS_DATABASE.AGC,
      stopSequence: 3,
      scheduledArrival: "07:50 AM",
      actualArrival: "07:50 AM",
      scheduledDeparture: "07:55 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 195,
      platform: 1,
      status: "CURRENT",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.GWL,
      stopSequence: 4,
      scheduledArrival: "09:23 AM",
      estimatedArrival: "09:23 AM",
      scheduledDeparture: "09:28 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 313,
      platform: 1,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: false, pharmacy: false },
    },
    {
      station: STATIONS_DATABASE.VGLJ,
      stopSequence: 5,
      scheduledArrival: "10:45 AM",
      estimatedArrival: "10:45 AM",
      scheduledDeparture: "10:53 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 410,
      platform: 1,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: false },
    },
    {
      station: STATIONS_DATABASE.BPL,
      stopSequence: 6,
      scheduledArrival: "02:05 PM",
      estimatedArrival: "02:05 PM",
      delayMinutes: 0,
      distanceFromOriginKm: 707,
      platform: 1,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
  ],

  // 12229 Lucknow Mail: LJN -> BE -> MB -> NDLS
  "12229": [
    {
      station: STATIONS_DATABASE.LJN,
      stopSequence: 1,
      scheduledDeparture: "10:00 PM",
      actualDeparture: "10:00 PM",
      delayMinutes: 0,
      distanceFromOriginKm: 0,
      platform: 6,
      status: "COMPLETED",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
    {
      station: STATIONS_DATABASE.BE,
      stopSequence: 2,
      scheduledArrival: "01:38 AM",
      actualArrival: "01:38 AM",
      scheduledDeparture: "01:43 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 235,
      platform: 2,
      status: "COMPLETED",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: false, pharmacy: false },
    },
    {
      station: STATIONS_DATABASE.MB,
      stopSequence: 3,
      scheduledArrival: "03:25 AM",
      estimatedArrival: "03:25 AM",
      scheduledDeparture: "03:33 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 325,
      platform: 3,
      status: "CURRENT",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: false },
    },
    {
      station: STATIONS_DATABASE.NDLS,
      stopSequence: 4,
      scheduledArrival: "06:55 AM",
      estimatedArrival: "06:55 AM",
      delayMinutes: 0,
      distanceFromOriginKm: 493,
      platform: 16,
      status: "UPCOMING",
      amenities: { food: true, waterRefill: true, wifi: true, lounge: true, pharmacy: true },
    },
  ],
};

export const GEOGRAPHIC_LANDMARKS: Record<string, GeographicLandmark[]> = {
  "12951": [
    {
      id: "thal-ghat",
      name: "Thal Ghat (Kasara Incline)",
      type: "ghat",
      latitude: 19.6865,
      longitude: 73.4862,
      description: "Picturesque Western Ghat railway section with gradient 1:37, viaducts, and tunnels.",
      elevationMeters: 580,
      distanceFromOriginKm: 120,
    },
    {
      id: "narmada-bridge",
      name: "Silver Jubilee Narmada Bridge",
      type: "bridge",
      latitude: 21.7051,
      longitude: 72.9959,
      description: "Historic 1.4km double-track railway bridge spanning the sacred Narmada river.",
      elevationMeters: 25,
      distanceFromOriginKm: 320,
    },
    {
      id: "chambal-ravines",
      name: "Chambal River & Kota Ravines",
      type: "river",
      latitude: 25.1852,
      longitude: 75.8344,
      description: "Dramatic sandstone gorge cut by the perennially flowing Chambal river.",
      elevationMeters: 245,
      distanceFromOriginKm: 915,
    },
  ],
  "22436": [
    {
      id: "yamuna-prayag",
      name: "Ganga-Yamuna Sangam",
      type: "river",
      latitude: 25.4294,
      longitude: 81.8841,
      description: "Sacred confluence of rivers Ganga, Yamuna, and mythical Saraswati.",
      elevationMeters: 92,
      distanceFromOriginKm: 638,
    },
  ],
};

export const STATION_AMENITIES_DATABASE: StationAmenityItem[] = [
  {
    id: "ST",
    stationCode: "ST",
    stationName: "Surat",
    hasFoodCourt: true,
    hasWifi: true,
    hasExecutiveLounge: true,
    hasPharmacy: false,
    hasRestrooms: true,
    hasWaterVending: true,
    hasStationMap: true,
  },
  {
    id: "BRC",
    stationCode: "BRC",
    stationName: "Vadodara",
    hasFoodCourt: true,
    hasWifi: true,
    hasExecutiveLounge: false,
    hasPharmacy: true,
    hasRestrooms: true,
    hasWaterVending: true,
    hasStationMap: true,
  },
  {
    id: "RTM",
    stationCode: "RTM",
    stationName: "Ratlam",
    hasFoodCourt: true,
    hasWifi: true,
    hasExecutiveLounge: false,
    hasPharmacy: false,
    hasRestrooms: true,
    hasWaterVending: true,
    hasStationMap: true,
  },
  {
    id: "CNB",
    stationCode: "CNB",
    stationName: "Kanpur Central",
    hasFoodCourt: true,
    hasWifi: true,
    hasExecutiveLounge: true,
    hasPharmacy: true,
    hasRestrooms: true,
    hasWaterVending: true,
    hasStationMap: true,
  },
];
